/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesGraficas;

import controle.ReceitaDespesaControle;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.entidades.ReceitaDespesa;

/**
 *
 * @author mathe
 */
public class Inicial extends javax.swing.JFrame {

    ReceitaDespesaControle rdControle = new ReceitaDespesaControle();
    public Inicial() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            mostrarListagem();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    private void mostrarListagem() throws Exception {
        try {
            ArrayList<ReceitaDespesa> receitasDespesas = rdControle.listagem();
            DefaultTableModel model = (DefaultTableModel) jTableRD.getModel();
            model.setNumRows(0);

            for (ReceitaDespesa receitaDespesa : receitasDespesas) {
                String[] receitasSeparadas = new String[9];
                receitasSeparadas[0] = receitaDespesa.getId() + "";
                receitasSeparadas[1] = receitaDespesa.getNome();
                receitasSeparadas[2] = receitaDespesa.getTipoReceita();
                receitasSeparadas[3] = receitaDespesa.getDataDaCompra();
                receitasSeparadas[4] = receitaDespesa.getCategoria();
                receitasSeparadas[5] = "R$ " + receitaDespesa.getValor().toString();
                receitasSeparadas[6] = receitaDespesa.getParcelaAtual() + " / " + receitaDespesa.getParcela();
                receitasSeparadas[7] = receitaDespesa.getTipoEntrada();
                receitasSeparadas[8] = receitaDespesa.isRepetitivo() == true ? "Repetitivo" : "Não repetitivo";
                model.addRow(receitasSeparadas);
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonReceitaDespesas = new javax.swing.JButton();
        jButtonCategoriaReceitaDespesas = new javax.swing.JButton();
        jButtonContaCorrente = new javax.swing.JButton();
        jButtonCartoes = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonBanco = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRD = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bem vindo ao CWallet");

        jPanel2.setBackground(new java.awt.Color(51, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(101, 111, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonReceitaDespesas.setBackground(new java.awt.Color(255, 255, 255));
        jButtonReceitaDespesas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonReceitaDespesas.setText("RECEITAS E DESPESAS");
        jButtonReceitaDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReceitaDespesasActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonReceitaDespesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 146, 357, 50));

        jButtonCategoriaReceitaDespesas.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCategoriaReceitaDespesas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonCategoriaReceitaDespesas.setText("CATEGORIAS DE RECEITA/DESPESA");
        jButtonCategoriaReceitaDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoriaReceitaDespesasActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCategoriaReceitaDespesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 246, -1, 50));

        jButtonContaCorrente.setBackground(new java.awt.Color(255, 255, 255));
        jButtonContaCorrente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonContaCorrente.setText("CONTA CORRENTE");
        jButtonContaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContaCorrenteActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonContaCorrente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 357, 50));

        jButtonCartoes.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCartoes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonCartoes.setText("CARTÕES");
        jButtonCartoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCartoesActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCartoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 357, 50));

        jLabel8.setFont(new java.awt.Font("Iosevka Fixed", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("C'Wallet");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, -1, -1));

        jLabel2.setFont(new java.awt.Font("Iosevka Fixed", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seja Bem-vindo");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 42, -1, -1));

        jButtonBanco.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBanco.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonBanco.setText("BANCOS");
        jButtonBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBancoActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 357, 50));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 608));

        jLabel1.setFont(new java.awt.Font("Iosevka Fixed", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RECEITAS DE ESPESAS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, -1, -1));

        jTableRD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Descrição", "Forma de pagamento", "Data da compra", "Categoria", "Valor", "Parcelas", "Tipo de receita", "Repetitivo"
            }
        ));
        jScrollPane2.setViewportView(jTableRD);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 790, 470));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1241, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 21, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 20, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReceitaDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReceitaDespesasActionPerformed
        ReceitaDespesaIG rd = new ReceitaDespesaIG();
        this.setVisible(false);
        rd.setVisible(true);
    }//GEN-LAST:event_jButtonReceitaDespesasActionPerformed

    private void jButtonCategoriaReceitaDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriaReceitaDespesasActionPerformed
        CategoriaIG categoria = new CategoriaIG();
        this.setVisible(false);
        categoria.setVisible(true);
    }//GEN-LAST:event_jButtonCategoriaReceitaDespesasActionPerformed

    private void jButtonContaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContaCorrenteActionPerformed
        try {
            TelaDeContas contas = new TelaDeContas();
            this.setVisible(false);
            contas.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonContaCorrenteActionPerformed

    private void jButtonCartoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCartoesActionPerformed
        try {
            TelaCartao cartao = new TelaCartao();
            this.setVisible(false);
            cartao.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonCartoesActionPerformed

    private void jButtonBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBancoActionPerformed
        try {
            TelaBanco banco = new TelaBanco();
            this.setVisible(false);
            banco.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonBancoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBanco;
    private javax.swing.JButton jButtonCartoes;
    private javax.swing.JButton jButtonCategoriaReceitaDespesas;
    private javax.swing.JButton jButtonContaCorrente;
    private javax.swing.JButton jButtonReceitaDespesas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableRD;
    // End of variables declaration//GEN-END:variables
}
