/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesGraficas;

import Controle.CategoriaControle;
import Controle.ReceitaDespesaControle;
import java.util.ArrayList;
import modelos.entidades.Categoria;
import modelos.entidades.ReceitaDespesa;
import java.math.BigDecimal;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mathe
 */
public class ReceitaDespesaIG extends javax.swing.JFrame {

    CategoriaControle categoriaControler = new CategoriaControle();
    ReceitaDespesaControle rdControle = new ReceitaDespesaControle();

    /**
     * Creates new form ReceitaDespesa
     */
    public ReceitaDespesaIG() {
        initComponents();
        try {
            mostrarListagem();
            limparTela();
            montarComboCategoria();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }

    private void montarComboCategoria() {
        try {
            ArrayList<Categoria> categorias = categoriaControler.listagem();
            String[] categoriasArray = new String[categorias.size()];
            for (int index = 0; index < categorias.size(); index++) {
                categoriasArray[index] = categorias.get(index).getNome();
            }
            DefaultComboBoxModel model = new DefaultComboBoxModel(categoriasArray);
            jComboBoxCategoria.setModel(model);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }

    private void limparTela() {
        jTextFieldId.setText("");
        jTextFieldDescricao.setText("");
        jFormattedTextFieldDataCompra.setText(" / ");
        jFormattedTextFieldDataCompra.setText("");
        jFormattedTextFieldDataCompra.setText(" / ");
        jRadioButtonReceita.setSelected(true);
        montarComboCategoria();
    }

    private void mostrarListagem() throws Exception {
        try {
            ArrayList<ReceitaDespesa> receitasDespesas = rdControle.listagem();
            DefaultTableModel model = (DefaultTableModel) jTableRD.getModel();
            model.setNumRows(0);

            for (ReceitaDespesa receitaDespesa : receitasDespesas) {
                String[] receitasSeparadas = new String[9];
                receitasSeparadas[0] = receitaDespesa.getId() + "";
                receitasSeparadas[1] = receitaDespesa.getNome();
                receitasSeparadas[2] = receitaDespesa.getTipoReceita();
                receitasSeparadas[3] = receitaDespesa.getDataDaCompra();
                receitasSeparadas[4] = receitaDespesa.getCategoria();
                receitasSeparadas[5] = "R$ " + receitaDespesa.getValor().toString();
                receitasSeparadas[6] = receitaDespesa.getParcelaAtual() + " / " + receitaDespesa.getParcela();
                receitasSeparadas[7] = receitaDespesa.getTipoEntrada();
                receitasSeparadas[8] = receitaDespesa.isRepetitivo() == true ? "Repetitivo" : "Não repetitivo";
                model.addRow(receitasSeparadas);
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoDeBotaoTipoEntrada = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jPanelLateralEsquerda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonIncluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        ConsultaPorId = new javax.swing.JButton();
        Listar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButtonCusto = new javax.swing.JRadioButton();
        jRadioButtonReceita = new javax.swing.JRadioButton();
        jRadioButtonRepetitivo = new javax.swing.JRadioButton();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldDescricao = new javax.swing.JTextField();
        jFormattedTextFieldParcelas = new javax.swing.JFormattedTextField();
        jTextFieldValor = new javax.swing.JTextField();
        jComboBoxFormaPagamento = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRD = new javax.swing.JTable();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jFormattedTextFieldDataCompra = new javax.swing.JFormattedTextField();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Receitas e Despesas");
        setMinimumSize(new java.awt.Dimension(1600, 900));

        jPanelLateralEsquerda.setBackground(new java.awt.Color(102, 102, 255));
        jPanelLateralEsquerda.setMinimumSize(new java.awt.Dimension(200, 200));
        jPanelLateralEsquerda.setPreferredSize(new java.awt.Dimension(200, 900));
        jPanelLateralEsquerda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("C'Wallet");
        jPanelLateralEsquerda.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 34, -1, -1));

        jButtonIncluir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonIncluir.setText("Confirmar");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });
        jPanelLateralEsquerda.add(jButtonIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 180, -1));

        jButtonEditar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanelLateralEsquerda.add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 210, 180, -1));

        ConsultaPorId.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ConsultaPorId.setText("consultar pro ID");
        ConsultaPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaPorIdActionPerformed(evt);
            }
        });
        jPanelLateralEsquerda.add(ConsultaPorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 180, -1));

        Listar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Listar.setText("Listar");
        Listar.setPreferredSize(new java.awt.Dimension(171, 33));
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });
        jPanelLateralEsquerda.add(Listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 352, 180, -1));

        jButtonExcluir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setPreferredSize(new java.awt.Dimension(171, 33));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanelLateralEsquerda.add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 180, -1));

        jButtonSair.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jPanelLateralEsquerda.add(jButtonSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 180, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Forma de pagamento");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Descrição");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Parcelas");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Data da compra");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Categoria");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Valor");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, -1));

        GrupoDeBotaoTipoEntrada.add(jRadioButtonCusto);
        jRadioButtonCusto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jRadioButtonCusto.setText("Custo");
        jRadioButtonCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCustoActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonCusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, -1, -1));

        GrupoDeBotaoTipoEntrada.add(jRadioButtonReceita);
        jRadioButtonReceita.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jRadioButtonReceita.setText("Receita");
        jRadioButtonReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonReceitaActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonReceita, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, -1, -1));

        jRadioButtonRepetitivo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jRadioButtonRepetitivo.setText("Repetitivo");
        jRadioButtonRepetitivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRepetitivoActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonRepetitivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, -1, -1));

        jTextFieldId.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel2.add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 400, -1));

        jTextFieldDescricao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel2.add(jTextFieldDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 400, -1));

        try {
            jFormattedTextFieldParcelas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldParcelas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel2.add(jFormattedTextFieldParcelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 400, -1));

        jTextFieldValor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel2.add(jTextFieldValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 400, -1));

        jComboBoxFormaPagamento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBoxFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cartao", "Dinheiro", "Conta" }));
        jComboBoxFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFormaPagamentoActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxFormaPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 400, -1));

        jTableRD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Descrição", "Forma de pagamento", "Data da compra", "Categoria", "Valor", "Parcelas", "Tipo de receita", "Repetitiva"
            }
        ));
        jScrollPane1.setViewportView(jTableRD);
        if (jTableRD.getColumnModel().getColumnCount() > 0) {
            jTableRD.getColumnModel().getColumn(8).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1390, 620));

        jComboBoxCategoria.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, 400, -1));

        try {
            jFormattedTextFieldDataCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataCompra.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel2.add(jFormattedTextFieldDataCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 400, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelLateralEsquerda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1394, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLateralEsquerda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCustoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCustoActionPerformed

    private void jRadioButtonReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonReceitaActionPerformed

    private void jRadioButtonRepetitivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRepetitivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonRepetitivoActionPerformed

    private void jComboBoxFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFormaPagamentoActionPerformed

    }//GEN-LAST:event_jComboBoxFormaPagamentoActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        try {
            ReceitaDespesa rd = new ReceitaDespesa();
            if (jTextFieldId.getText().isEmpty() || jTextFieldId.getText() == " ") {
                throw new Exception("Por favor preenchar o campo de ID");
            }
            String[] parcelasSeparadas = jFormattedTextFieldParcelas.getText().split("/");
            rd.setId(Integer.parseInt(jTextFieldId.getText()));
            rd.setNome(jTextFieldDescricao.getText());
            rd.setTipoReceita(jComboBoxFormaPagamento.getSelectedItem().toString());
            rd.setDataDaCompra(jFormattedTextFieldDataCompra.getText());
            rd.setCategoria(jComboBoxCategoria.getSelectedItem().toString());
            rd.setValor(new BigDecimal(jTextFieldValor.getText()));
            rd.setParcelaAtual(Integer.parseInt(parcelasSeparadas[0]));
            rd.setParcela(Integer.parseInt(parcelasSeparadas[1]));
            if (jRadioButtonReceita.isSelected()) {
                rd.setTipoEntrada("Receita");
            } else {
                rd.setTipoEntrada("Custo");
            }
            rd.setRepetitivo(jRadioButtonRepetitivo.isSelected());
            rdControle.incluir(rd);
            limparTela();
            mostrarListagem();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        try {
            if (jTextFieldId.getText().isEmpty() || jTextFieldId.getText() == " ") {
                throw new Exception("Por favor preenchar o campo de ID");
            }
            if (jTextFieldDescricao.getText().isEmpty() || jTextFieldDescricao.getText().equals("")) {
                throw new Exception("Digite algum valor no campo de descrição, por favor.");
            }
            String str = jTextFieldId.getText();
            int id = Integer.parseInt(str);
            ReceitaDespesa rdModificada = new ReceitaDespesa();
            String[] parcelasSeparadas = jFormattedTextFieldParcelas.getText().split("/");
            rdModificada.setId(Integer.parseInt(jTextFieldId.getText()));
            rdModificada.setNome(jTextFieldDescricao.getText());
            rdModificada.setTipoReceita(jComboBoxFormaPagamento.getSelectedItem().toString());
            rdModificada.setDataDaCompra(jFormattedTextFieldDataCompra.getText());
            rdModificada.setCategoria(jComboBoxCategoria.getSelectedItem().toString());
            rdModificada.setValor(new BigDecimal(jTextFieldValor.getText()));
            rdModificada.setParcelaAtual(Integer.parseInt(parcelasSeparadas[0]));
            rdModificada.setParcela(Integer.parseInt(parcelasSeparadas[1]));
            if (jRadioButtonReceita.isSelected()) {
                rdModificada.setTipoEntrada("Receita");
            } else {
                rdModificada.setTipoEntrada("Custo");
            }
            rdModificada.setRepetitivo(jRadioButtonRepetitivo.isSelected());

            rdControle.alterar(rdModificada);
            limparTela();
            mostrarListagem();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void ConsultaPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaPorIdActionPerformed
        try {
            String str = jTextFieldId.getText();
            DefaultTableModel model = (DefaultTableModel) jTableRD.getModel();
            model.setNumRows(0);
            if (str.length() == 0) {
                limparTela();
                mostrarListagem();
                throw new Exception("O Identificador esta VAZIO!");
            }
            int id = Integer.parseInt(str);
            ReceitaDespesa rd = rdControle.consultarPorId(id);
            if (rd == null) {
                limparTela();
                mostrarListagem();
                throw new Exception("Categoria não existe no sistema");
            }
            String[] receitasSeparadas = new String[9];
            receitasSeparadas[0] = rd.getId() + "";
            receitasSeparadas[1] = rd.getNome();
            receitasSeparadas[2] = rd.getTipoReceita();
            receitasSeparadas[3] = rd.getDataDaCompra();
            receitasSeparadas[4] = rd.getCategoria();
            receitasSeparadas[5] = "R$ " + rd.getValor().toString();
            receitasSeparadas[6] = rd.getParcelaAtual() + " / " + rd.getParcela();
            receitasSeparadas[7] = rd.getTipoEntrada();
            receitasSeparadas[8] = rd.isRepetitivo() == true ? "Repetitivo" : "Não repetitivo";
            model.addRow(receitasSeparadas);
            limparTela();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_ConsultaPorIdActionPerformed

    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
        try {
            mostrarListagem();
        } catch (Exception ex) {
            Logger.getLogger(CategoriaIG.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ListarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        try {
            if (jTextFieldId.getText().isEmpty() || jTextFieldId.getText().equals(" ")) {
                throw new Exception("Por favor, adicione o ID");
            }
            int id = Integer.parseInt(jTextFieldId.getText());
            if (JOptionPane.showConfirmDialog(null, "Deseja realmente exlcuir esse dado?") == 0) {
                rdControle.apagarPorId(id);
                limparTela();
                mostrarListagem();
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceitaDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceitaDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceitaDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ReceitaDespesa.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceitaDespesaIG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultaPorId;
    private javax.swing.ButtonGroup GrupoDeBotaoTipoEntrada;
    private javax.swing.JButton Listar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxFormaPagamento;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataCompra;
    private javax.swing.JFormattedTextField jFormattedTextFieldParcelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelLateralEsquerda;
    private javax.swing.JRadioButton jRadioButtonCusto;
    private javax.swing.JRadioButton jRadioButtonReceita;
    private javax.swing.JRadioButton jRadioButtonRepetitivo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRD;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
