/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacesGraficas;

import javax.swing.JOptionPane;
import modelos.entidades.Banco;
import controle.BancoControle;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author João
 */
public class TelaBanco extends javax.swing.JFrame {

    BancoControle objBancoControle = new BancoControle();

    /**
     * Creates new form TelaTeste
     */
    public TelaBanco() throws Exception {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrarListagem();

    }

    public void limparTela() {
        jTextFieldIdentificador.setText("");
        jTextFieldDescricao.setText("");
    }

    private void mostrarListagem() throws Exception {
        try {
            ArrayList<Banco> arrayDosBancos = objBancoControle.listagem();
            DefaultTableModel model = (DefaultTableModel) jTableBancos.getModel();
            model.setNumRows(0);

            for (int pos = 0; pos < arrayDosBancos.size(); pos++) {
                String[] saida = new String[2];
                Banco aux = arrayDosBancos.get(pos);
                saida[0] = aux.getId() + "";
                saida[1] = aux.getDescricao();
                model.addRow(saida);

            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonIncluir = new javax.swing.JButton();
        jButtonExluirPorId = new javax.swing.JButton();
        jButtonConsultarPorId = new javax.swing.JButton();
        jButtonAlterarPorId = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBancos = new javax.swing.JTable();
        jTextFieldIdentificador = new javax.swing.JTextField();
        jTextFieldDescricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE CONTROLE FINANCEIRO");
        setBackground(new java.awt.Color(51, 255, 102));

        jPanel1.setBackground(new java.awt.Color(101, 111, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(174, 463));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Iosevka Fixed", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("C'Wallet");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 41, -1, -1));

        jButtonIncluir.setFont(new java.awt.Font("Iosevka", 1, 14)); // NOI18N
        jButtonIncluir.setText("Cadastrar");
        jButtonIncluir.setPreferredSize(new java.awt.Dimension(142, 35));
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 175, -1, -1));

        jButtonExluirPorId.setFont(new java.awt.Font("Iosevka", 1, 14)); // NOI18N
        jButtonExluirPorId.setText("Excluir Por ID");
        jButtonExluirPorId.setPreferredSize(new java.awt.Dimension(142, 35));
        jButtonExluirPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExluirPorIdActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExluirPorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 244, -1, -1));

        jButtonConsultarPorId.setFont(new java.awt.Font("Iosevka", 1, 14)); // NOI18N
        jButtonConsultarPorId.setText("Consultar por ID");
        jButtonConsultarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarPorIdActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonConsultarPorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 313, -1, -1));

        jButtonAlterarPorId.setFont(new java.awt.Font("Iosevka", 1, 14)); // NOI18N
        jButtonAlterarPorId.setText("Alterar Por ID");
        jButtonAlterarPorId.setPreferredSize(new java.awt.Dimension(142, 35));
        jButtonAlterarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarPorIdActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAlterarPorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 374, -1, -1));

        jButtonVoltar.setFont(new java.awt.Font("Iosevka", 1, 14)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setPreferredSize(new java.awt.Dimension(142, 35));
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 153, 0));

        jTableBancos.setFont(new java.awt.Font("Iosevka", 1, 14)); // NOI18N
        jTableBancos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Nome do Banco"
            }
        ));
        jScrollPane1.setViewportView(jTableBancos);

        jTextFieldIdentificador.setFont(new java.awt.Font("Iosevka", 0, 14)); // NOI18N

        jTextFieldDescricao.setFont(new java.awt.Font("Iosevka", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Iosevka", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descrição");

        jLabel2.setFont(new java.awt.Font("Iosevka", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Identificador");

        jLabel4.setFont(new java.awt.Font("Iosevka Fixed", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lista de Bancos Cadastrados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(99, 99, 99))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(jTextFieldIdentificador.getText());
            String nomeDoBanco = jTextFieldDescricao.getText();

            Banco objBanco = new Banco(id, nomeDoBanco);

            objBancoControle.incluir(objBanco);
            limparTela();
            mostrarListagem();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonConsultarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarPorIdActionPerformed
        // TODO add your handling code here:
        try {
            String str = jTextFieldIdentificador.getText();
            int id = Integer.parseInt(str);

            if (str.length() == 0) {
                throw new Exception("O Identificador esta VAZIO!");
            }

            Banco objBanco = objBancoControle.consultarPorId(id);
            if (objBanco == null) {
                throw new Exception("Banco não existe no sistema");
            }

            jTextFieldIdentificador.setText(objBanco.getId() + "");
            jTextFieldDescricao.setText(objBanco.getDescricao() + "");

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonConsultarPorIdActionPerformed

    private void jButtonExluirPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExluirPorIdActionPerformed
        // TODO add your handling code here:
        try {
            String str = jTextFieldIdentificador.getText();
            int id = Integer.parseInt(str);

            if (str.length() == 0) {
                throw new Exception("O Identificador esta VAZIO!");
            }
            
            Banco objBanco = objBancoControle.consultarPorId(id);
            if (objBanco == null) {
                throw new Exception("Banco não existe no sistema");
            }

            objBancoControle.apagarPorId(id);
            limparTela();
            mostrarListagem();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonExluirPorIdActionPerformed

    private void jButtonAlterarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarPorIdActionPerformed
        // TODO add your handling code here:

        try {
            //Validar campos 
            String str = jTextFieldIdentificador.getText();
            int id = Integer.parseInt(str);
            if (str.length() == 0) {
                throw new Exception("O Identificador esta VAZIO!");
            }
            Banco objBanco = objBancoControle.consultarPorId(id);
            if (objBanco == null) {
                throw new Exception("Banco não existe no sistema");
            }
            
            String nomeDoBanco = jTextFieldDescricao.getText();
            Banco objBanco1 = new Banco(id, nomeDoBanco);
            
            objBancoControle.alterar(objBanco1);
            limparTela();
            mostrarListagem();
            

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonAlterarPorIdActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        Inicial inicial = new Inicial();
        inicial.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaBanco().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(TelaBanco.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarPorId;
    private javax.swing.JButton jButtonConsultarPorId;
    private javax.swing.JButton jButtonExluirPorId;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBancos;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldIdentificador;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
