/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesGraficas;

import controle.UsuarioControle;
import javax.swing.JOptionPane;
import modelos.entidades.Usuarios;

/**
 *
 * @author luisg
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void limparTela(){
        jTextFieldCPF.setText("");
        jTextFieldSenha.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JbuttonConfirmar = new javax.swing.JButton();
        jButtonNovoUsuario = new javax.swing.JButton();
        jTextFieldSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setMinimumSize(new java.awt.Dimension(380, 330));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelPrincipal.setBackground(new java.awt.Color(101, 111, 255));
        PainelPrincipal.setMaximumSize(new java.awt.Dimension(380, 330));
        PainelPrincipal.setMinimumSize(new java.awt.Dimension(380, 330));
        PainelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("C'Wallet");
        jLabel1.setMaximumSize(new java.awt.Dimension(380, 128));
        PainelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 57, 352, -1));

        jLabelCPF.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelCPF.setText("C.P.F :");
        PainelPrincipal.add(jLabelCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 111, -1, -1));

        jTextFieldCPF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PainelPrincipal.add(jTextFieldCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 141, 253, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Senha :");
        PainelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 189, -1, -1));

        JbuttonConfirmar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JbuttonConfirmar.setText("Confirmar");
        JbuttonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbuttonConfirmarActionPerformed(evt);
            }
        });
        PainelPrincipal.add(JbuttonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        jButtonNovoUsuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonNovoUsuario.setText("Novo Usuario");
        jButtonNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoUsuarioActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jButtonNovoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jTextFieldSenha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PainelPrincipal.add(jTextFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 260, 40));

        getContentPane().add(PainelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbuttonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbuttonConfirmarActionPerformed
        try {
            UsuarioControle uc = new UsuarioControle();
            String cpf = jTextFieldCPF.getText();
            String senha = jTextFieldSenha.getText();
            Usuarios usuario = uc.consultarPorCPF(cpf);
            if(jTextFieldCPF.equals("") || jTextFieldCPF.getText().isEmpty()){
                throw new Exception("O campo CPF deve ser preenchido.");
            }
            if(usuario == null){
                throw new Exception("O usuário não existe");
            }
            if(senha.equals(usuario.getSenha())){
                Inicial inicial = new Inicial();
                inicial.setVisible(true);
                this.setVisible(false);
            }else{
                throw new Exception("A senha informada está errada, por favor digite novamente.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            limparTela();
        }
    }//GEN-LAST:event_JbuttonConfirmarActionPerformed

    private void jButtonNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoUsuarioActionPerformed
        TelaCadastroDeUsuario tcu = new TelaCadastroDeUsuario();
        this.setVisible(false);
        tcu.setVisible(true);
    }//GEN-LAST:event_jButtonNovoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbuttonConfirmar;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JButton jButtonNovoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JPasswordField jTextFieldSenha;
    // End of variables declaration//GEN-END:variables
}
